service:
  name: aws-nodejs-typescript
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: handler.hello
    name: ${self:service}-api-${self:provider.stage}
    events:
      - http:
          method: get
          path: hello
  world:
    handler: handler.world
    name: ${self:service}-api-${self:provider.stage}
    events:
      - http:
          method: get
          path: world
